### ISSUE TITLE
Minor feedback

### ISSUE THREAD

**Issue by luciusmagn** [codekopf/robotdreams-rustdeveloper#1]
https://github.com/codekopf/robotdreams-rustdeveloper/blob/1968702fbe13a67024e45a14822e791a5d9390a1/lecture02homework/src/main.rs#L3

You don't need this import, since you are not using it (you can reference top-level paths just like that)

https://github.com/codekopf/robotdreams-rustdeveloper/blob/1968702fbe13a67024e45a14822e791a5d9390a1/lecture02homework/src/main.rs#L22

Use `.is_empty()` instead.

When you are replacing just one char with a string, you can use a char literal in a replace like `.replace(' ', "")`

**Comment by codekopf** [comment]
Issues addressed in [4545cc1](https://github.com/codekopf/robotdreams-rustdeveloper/commit/4545cc1bb2ae42550f6ecd1ac5dd893200b3d080)

Closing the issue.
